const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const translations={en:{addImage:'＋ Add New Image'},id:{addImage:'＋ Tambah Gambar Baru'},ja:{addImage:'＋ 新しい画像'},ko:{addImage:'＋ 새 이미지'},es:{addImage:'＋ Nueva imagen'},zh:{addImage:'＋ 新建图像'}};
const features=[['✏️','Sketch','Pencil, pen and charcoal presets'],['🎨','Coloring','Palette, fill, gradient and picker'],['◐','Shadowing','Soft, hard and directional light'],['⌁','Perspective','1, 2, 3 point and isometric guides'],['▱','Layers','Organize sketch, color and effects'],['🖼️','Import Images','JPG, PNG and WEBP'],['⇩','Export','PNG, JPG, WEBP and PDF'],['◎','Symmetry','Vertical, horizontal and radial']];
$('#featureGrid').innerHTML=features.map(x=>`<div class="feature-card"><b>${x[0]} ${x[1]}</b><span>${x[2]}</span></div>`).join('');
const shortcuts=[['Ctrl + Z','Undo'],['Ctrl + Y','Redo'],['Ctrl + S','Save'],['Ctrl + Shift + S','Save As'],['Ctrl + C','Copy'],['Ctrl + V','Paste'],['Ctrl + X','Cut'],['Ctrl + A','Select All'],['Ctrl + D','Deselect'],['Ctrl + T','Transform'],['Ctrl + Plus','Zoom In'],['Ctrl + Minus','Zoom Out'],['Space + Drag','Pan'],['B','Brush'],['P','Pencil'],['E','Eraser'],['G','Fill'],['I','Eyedropper'],['L','Line'],['R','Rectangle'],['O','Circle'],['T','Text'],['M','Move'],['C','Crop'],['F','Fullscreen'],['H','Hand/Pan'],['Shift + B','Brush Settings'],['Shift + E','Eraser'],['Shift + L','Line'],['Shift + R','Rectangle'],['Shift + O','Circle'],['Shift + P','Perspective'],['Shift + S','Symmetry'],['Ctrl + 0','Fit Canvas'],['Ctrl + 1','100% Zoom'],['Ctrl + 2','200% Zoom'],['[','Decrease Brush Size'],[']','Increase Brush Size'],['X','Swap Colors'],['D','Reset Colors'],['Delete','Delete Selection'],['Ctrl + Shift + N','New Layer'],['Ctrl + Shift + E','Merge Layers'],['Shift + Drag','Constrain Movement'],['Alt + Click','Sample Color'],['Tab','Hide UI'],['Ctrl + Shift + Z','Redo'],['Ctrl + Plus','Increase Zoom'],['Ctrl + Minus','Decrease Zoom'],['Esc','Cancel Current Action'],['Ctrl + I','Import Image'],['Ctrl + G','Toggle Guides'],['Ctrl + Shift + P','Perspective Panel']];
$('#shortcutList').innerHTML=shortcuts.map(s=>`<div class="shortcut"><span>${s[1]}</span><kbd>${s[0]}</kbd></div>`).join('');

let canvas=$('#canvas'), ctx=canvas.getContext('2d',{willReadFrequently:true}), guide=$('#guideCanvas'), gctx=guide.getContext('2d');
let state={w:1200,h:800,zoom:1,rotation:0,tool:'brush',color:'#ffffff',size:8,opacity:1,hardness:.8,flow:1,smooth:.2,drawing:false,last:null,start:null,history:[],future:[],layers:[],active:0,sym:'none',perspective:false,viewX:0,viewY:0,pan:false};
function fit(){const r=$('#canvasWrap').getBoundingClientRect();state.zoom=Math.min((r.width-30)/state.w,(r.height-30)/state.h,1);renderView()}
function renderView(){[canvas,guide].forEach(c=>{c.style.width=state.w*state.zoom+'px';c.style.height=state.h*state.zoom+'px';c.style.transform=`translate(-50%,-50%) rotate(${state.rotation}deg) translate(${state.viewX/state.zoom}px,${state.viewY/state.zoom}px)`});$('#zoomLabel').textContent=Math.round(state.zoom*100)+'%';drawGuides()}
function snapshot(){return canvas.toDataURL('image/png')}
function restore(url){const im=new Image();im.onload=()=>{ctx.clearRect(0,0,state.w,state.h);ctx.drawImage(im,0,0);renderLayers();renderView()};im.src=url}
function pushHistory(){state.history.push(snapshot());if(state.history.length>30)state.history.shift();state.future=[]}
function undo(){if(!state.history.length)return;state.future.push(snapshot());restore(state.history.pop())}
function redo(){if(!state.future.length)return;state.history.push(snapshot());restore(state.future.pop())}
function setupCanvas(w=1200,h=800,bg='white'){state.w=w;state.h=h;canvas.width=w;canvas.height=h;guide.width=w;guide.height=h;ctx.clearRect(0,0,w,h);if(bg==='white'){ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h)}else if(bg==='green'){ctx.fillStyle='#00a86b';ctx.fillRect(0,0,w,h)}else if(bg==='custom'){ctx.fillStyle=$('#bgColor').value;ctx.fillRect(0,0,w,h)}state.layers=[{name:'Background',visible:true,locked:false,opacity:1,data:canvas.toDataURL()}];state.active=0;state.history=[];state.future=[];$('#emptyHint').classList.add('hidden');renderLayers();fit();saveProjectAuto()}
function pos(e){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/state.zoom,y=(e.clientY-r.top)/state.zoom;return{x,y}}
function setBrush(){ctx.globalAlpha=state.opacity;ctx.globalCompositeOperation=state.tool==='eraser'?'destination-out':'source-over';let c=state.color;if(state.tool==='pencil')ctx.globalAlpha*=.7;if(state.tool==='marker')ctx.globalAlpha*=.35;if(state.tool==='highlight'){c='#fff59a';ctx.globalAlpha*=.5}if(state.tool==='shadow'){c='#000';ctx.globalAlpha*=+$('#shadowIntensity').value/100}ctx.strokeStyle=c;ctx.fillStyle=c;ctx.lineWidth=state.size;ctx.lineCap='round';ctx.lineJoin='round';ctx.shadowBlur=state.tool==='shadow'?+$('#shadowSoftness').value/2:0;ctx.shadowColor=c}
function drawDot(p){setBrush();ctx.beginPath();ctx.arc(p.x,p.y,state.size/2,0,Math.PI*2);ctx.fill();applySymmetry('dot',p)}
function stroke(a,b){setBrush();ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();applySymmetry('line',a,b)}
function applySymmetry(type,a,b){const modes=state.sym==='vertical'?[{x:-1}]:state.sym==='horizontal'?[{y:-1}]:state.sym==='radial'?[{a:Math.PI/2},{a:Math.PI},{a:3*Math.PI/2}]:[];for(const m of modes){let ax=a.x,ay=a.y,bx=b?.x,by=b?.y;if(m.x)ax=state.w-ax;if(m.x&&b)bx=state.w-bx;if(m.y)ay=state.h-ay;if(m.y&&b)by=state.h-by;if(m.a!==undefined){const cx=state.w/2,cy=state.h/2;const rot=(x,y)=>{let dx=x-cx,dy=y-cy;return{x:cx+dx*Math.cos(m.a)-dy*Math.sin(m.a),y:cy+dx*Math.sin(m.a)+dy*Math.cos(m.a)}};let q=rot(ax,ay);ax=q.x;ay=q.y;if(b){q=rot(bx,by);bx=q.x;by=q.y}}if(type==='dot'){ctx.beginPath();ctx.arc(ax,ay,state.size/2,0,Math.PI*2);ctx.fill()}else{ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(bx,by);ctx.stroke()}}}
function drawShape(a,b){setBrush();ctx.globalCompositeOperation='source-over';ctx.beginPath();if(state.tool==='line'){ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y)}else if(state.tool==='rect'){ctx.rect(a.x,a.y,b.x-a.x,b.y-a.y)}else{let rx=Math.abs(b.x-a.x)/2,ry=Math.abs(b.y-a.y)/2,cx=(a.x+b.x)/2,cy=(a.y+b.y)/2;ctx.ellipse(cx,cy,rx,ry,0,0,Math.PI*2)}ctx.stroke();}
function fillAt(p){setBrush();const img=ctx.getImageData(0,0,state.w,state.h),d=img.data,x=Math.floor(p.x),y=Math.floor(p.y);if(x<0||y<0||x>=state.w||y>=state.h)return;const i=(y*state.w+x)*4,target=[d[i],d[i+1],d[i+2],d[i+3]],hex=state.color.match(/[0-9a-f]{2}/gi).map(v=>parseInt(v,16)),q=[[x,y]],seen=new Uint8Array(state.w*state.h),tol=32;const same=k=>Math.abs(d[k]-target[0])<tol&&Math.abs(d[k+1]-target[1])<tol&&Math.abs(d[k+2]-target[2])<tol&&Math.abs(d[k+3]-target[3])<tol;while(q.length){const [px,py]=q.pop(),idx=py*state.w+px;if(idx<0||idx>=seen.length||seen[idx])continue;seen[idx]=1;const k=idx*4;if(!same(k))continue;d[k]=hex[0];d[k+1]=hex[1];d[k+2]=hex[2];d[k+3]=255;q.push([px+1,py],[px-1,py],[px,py+1],[px,py-1])}ctx.putImageData(img,0,0)}
function pointerDown(e){if(state.tool==='move'||state.pan){state.pan=true;state.last={x:e.clientX,y:e.clientY};return}const p=pos(e);state.drawing=true;state.start=p;state.last=p;pushHistory();if(state.tool==='fill')fillAt(p);else if(state.tool==='picker'){const d=ctx.getImageData(Math.floor(p.x),Math.floor(p.y),1,1).data;$('#color').value='#'+[d[0],d[1],d[2]].map(x=>x.toString(16).padStart(2,'0')).join('');state.color=$('#color').value}else if(state.tool==='text'){const t=prompt('Text');if(t){setBrush();ctx.font=`${Math.max(12,state.size*3)}px sans-serif`;ctx.fillText(t,p.x,p.y)}}else if(['line','rect','circle'].includes(state.tool)){}else drawDot(p);e.preventDefault()}
function pointerMove(e){if(state.pan&&!state.drawing&&state.last){state.viewX+=(e.clientX-state.last.x);state.viewY+=(e.clientY-state.last.y);state.last={x:e.clientX,y:e.clientY};renderView();return}if(!state.drawing)return;const p=pos(e);if(['line','rect','circle'].includes(state.tool)){restore(state.history[state.history.length-1]);drawShape(state.start,p)}else{stroke(state.last,p);state.last=p}e.preventDefault()}
function pointerUp(){if(state.drawing){state.drawing=false;state.last=null;renderLayers();saveProjectAuto()}}
canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);window.addEventListener('pointerup',pointerUp);
$('#color').oninput=e=>state.color=e.target.value;$('#size').oninput=e=>{state.size=+e.target.value;$('#sizeOut').textContent=e.target.value};$('#opacity').oninput=e=>{state.opacity=+e.target.value/100;$('#opacityOut').textContent=e.target.value+'%'};$('#hardness').oninput=e=>state.hardness=+e.target.value/100;$('#flow').oninput=e=>state.flow=+e.target.value/100;$('#smooth').oninput=e=>state.smooth=+e.target.value/100;
$$('.tool').forEach(b=>b.onclick=()=>{$$('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tool=b.dataset.tool;state.pan=state.tool==='move'});
$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#fitBtn').onclick=()=>{state.viewX=state.viewY=0;fit()};$('#zoomIn').onclick=()=>{state.zoom=Math.min(8,state.zoom*1.2);renderView()};$('#zoomOut').onclick=()=>{state.zoom=Math.max(.1,state.zoom/1.2);renderView()};$('#rotateBtn').onclick=()=>{state.rotation=(state.rotation+90)%360;renderView()};$('#panBtn').onclick=()=>{state.pan=!state.pan;toast(state.pan?'Pan enabled':'Pan disabled')};$('#swapColors').onclick=()=>{const c=state.color;state.color='#ffffff';$('#color').value=state.color};$('#resetColors').onclick=()=>{state.color='#000000';$('#color').value=state.color};$('#fullBtn').onclick=()=>document.documentElement.requestFullscreen?.();
$('#symBtn').onclick=()=>{state.sym=state.sym==='none'?'vertical':state.sym==='vertical'?'horizontal':state.sym==='horizontal'?'radial':'none';toast('Symmetry: '+state.sym);drawGuides()};$('#verticalSym').onclick=()=>{state.sym='vertical';drawGuides()};$('#horizontalSym').onclick=()=>{state.sym='horizontal';drawGuides()};$('#radialSym').onclick=()=>{state.sym='radial';drawGuides()};$('#perspBtn').onclick=()=>{$('#showPerspective').checked=!$('#showPerspective').checked;state.perspective=$('#showPerspective').checked;drawGuides()};$('#showPerspective').onchange=e=>{state.perspective=e.target.checked;drawGuides()};$('#perspectiveType').onchange=drawGuides;
function drawGuides(){gctx.clearRect(0,0,state.w,state.h);gctx.save();gctx.globalAlpha=.35;gctx.strokeStyle='#1688ff';gctx.lineWidth=1/state.zoom;const type=$('#perspectiveType').value;if(state.perspective){if(type==='1 Point'){const vx=state.w/2,vy=state.h/2;for(let x=0;x<=state.w;x+=80){gctx.beginPath();gctx.moveTo(x,0);gctx.lineTo(vx,vy);gctx.stroke();gctx.beginPath();gctx.moveTo(x,state.h);gctx.lineTo(vx,vy);gctx.stroke()}}else if(type==='2 Point'){for(const vx of [state.w*.1,state.w*.9]){for(let y=0;y<=state.h;y+=80){gctx.beginPath();gctx.moveTo(vx,state.h/2);gctx.lineTo(state.w/2,y);gctx.stroke()}}}else if(type==='3 Point'){const pts=[[state.w*.1,state.h*.5],[state.w*.9,state.h*.5],[state.w*.5,state.h*.05]];for(const [vx,vy] of pts)for(let i=0;i<10;i++){gctx.beginPath();gctx.moveTo(vx,vy);gctx.lineTo((i/9)*state.w,state.h*(i%2));gctx.stroke()}}else if(type==='Isometric'){for(let x=-state.h;x<state.w+state.h;x+=60){gctx.beginPath();gctx.moveTo(x,0);gctx.lineTo(x+state.h*.58,state.h);gctx.stroke();gctx.beginPath();gctx.moveTo(x,state.h);gctx.lineTo(x+state.h*.58,0);gctx.stroke()}}}if(state.sym!=='none'){gctx.strokeStyle='#fff';gctx.setLineDash([8,8]);gctx.beginPath();if(state.sym==='vertical'||state.sym==='radial'){gctx.moveTo(state.w/2,0);gctx.lineTo(state.w/2,state.h)}if(state.sym==='horizontal'||state.sym==='radial'){gctx.moveTo(0,state.h/2);gctx.lineTo(state.w,state.h/2)}gctx.stroke();gctx.setLineDash([])}gctx.restore()}
function renderLayers(){const box=$('#layers');box.innerHTML=state.layers.map((l,i)=>`<div class="layer ${i===state.active?'active':''}" data-i="${i}"><span>${l.visible?'👁':'◌'}</span><span style="flex:1">${l.name}</span><span>${Math.round(l.opacity*100)}%</span></div>`).join('');$$('.layer').forEach(x=>x.onclick=()=>{state.active=+x.dataset.i;renderLayers()})}
$('#addLayer').onclick=()=>{pushHistory();state.layers.splice(state.active+1,0,{name:'Layer '+(state.layers.length+1),visible:true,locked:false,opacity:1,data:canvas.toDataURL()});state.active++;renderLayers()};$('#dupLayer').onclick=()=>{pushHistory();state.layers.splice(state.active+1,0,{...state.layers[state.active],name:state.layers[state.active].name+' copy'});state.active++;renderLayers()};$('#delLayer').onclick=()=>{if(state.layers.length>1){pushHistory();state.layers.splice(state.active,1);state.active=Math.max(0,state.active-1);renderLayers()}};$('#mergeLayer').onclick=()=>toast('Layer merge: current raster is already composited in this lightweight workspace.');
const presets={A4:[2480,3508],A3:[3508,4961],A5:[1748,2480],Square:[1200,1200],Portrait:[800,1200],Landscape:[1200,800],'16:9':[1600,900],'4:3':[1200,900]};$('#presetGrid').innerHTML=Object.keys(presets).map(k=>`<button data-preset="${k}">${k}</button>`).join('');$$('[data-preset]').forEach(b=>b.onclick=()=>{$('#customW').value=presets[b.dataset.preset][0];$('#customH').value=presets[b.dataset.preset][1]});
function open(id){$('#'+id).classList.remove('hidden')}function close(id){$('#'+id).classList.add('hidden')}$$('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));$('#newBtn').onclick=()=>open('newModal');$('#startBtn').onclick=()=>{open('newModal')};$('#toolsBtn').onclick=()=>document.querySelector('.feature-section').scrollIntoView({behavior:'smooth'});$('#shortcutsBtn').onclick=()=>open('shortcutsModal');$('#galleryBtn').onclick=()=>{open('galleryModal');loadGallery()};$('#exportBtn').onclick=()=>open('exportModal');$('#createCanvas').onclick=()=>{setupCanvas(+$(' #customW').value||1200,+$('#customH').value||800,$('#bgType').value);close('newModal');$('#landing').classList.add('hidden');$('#studio').classList.remove('hidden')};
$('#fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const im=new Image();im.onload=()=>{pushHistory();ctx.drawImage(im,0,0,state.w,state.h);renderLayers();saveProjectAuto();URL.revokeObjectURL(im.src)};im.src=URL.createObjectURL(f)};document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('drop',e=>{e.preventDefault();if(e.dataTransfer.files[0]){$('#fileInput').files=e.dataTransfer.files;$('#fileInput').dispatchEvent(new Event('change'))}});
async function exportImage(type){const a=document.createElement('a');if(type==='pdf'){try{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';document.head.appendChild(s);await new Promise((res,rej)=>{s.onload=res;s.onerror=rej});const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:state.w>=state.h?'landscape':'portrait',unit:'px',format:[state.w,state.h]});pdf.addImage(canvas.toDataURL('image/jpeg',.95),'JPEG',0,0,state.w,state.h);pdf.save('origodraw.pdf')}catch(e){toast('PDF needs an internet connection for the PDF library.')}}else{a.href=canvas.toDataURL('image/'+type,type==='jpg'?.92:undefined);a.download='origodraw.'+(type==='jpg'?'jpg':type);a.click()}close('exportModal')}
$$('[data-export]').forEach(b=>b.onclick=()=>exportImage(b.dataset.export));
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
const dbp=new Promise((resolve,reject)=>{const r=indexedDB.open('OrigoDraw',1);r.onupgradeneeded=()=>r.result.createObjectStore('projects',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function saveProjectAuto(){try{const db=await dbp;const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put({id:'current',name:'Current Project',w:state.w,h:state.h,data:canvas.toDataURL(),updated:Date.now()})}catch(e){}}
async function loadGallery(){const db=await dbp,tx=db.transaction('projects','readonly'),req=tx.objectStore('projects').getAll();req.onsuccess=()=>{$('#gallery').innerHTML=req.result.map(p=>`<div class="gallery-item"><img src="${p.data}"><div class="meta"><b>${p.name}</b><div class="row"><button onclick="loadProject('${p.id}')">Open</button><button onclick="downloadProject('${p.id}')">Download</button></div></div></div>`).join('')||'<p class="muted">No projects yet.</p>'}}
window.loadProject=async id=>{const db=await dbp,tx=db.transaction('projects','readonly'),r=tx.objectStore('projects').get(id);r.onsuccess=()=>{const p=r.result;if(p){setupCanvas(p.w,p.h,'transparent');restore(p.data);close('galleryModal');$('#landing').classList.add('hidden');$('#studio').classList.remove('hidden')}}};window.downloadProject=async id=>{const db=await dbp,tx=db.transaction('projects','readonly'),r=tx.objectStore('projects').get(id);r.onsuccess=()=>{const a=document.createElement('a');a.href=r.result.data;a.download=r.result.name+'.png';a.click()}};
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('origodraw-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('origodraw-theme')==='light')document.body.classList.add('light');
$('#language').onchange=e=>{const t=translations[e.target.value]||translations.en;$$('[data-i18n]').forEach(x=>x.textContent=t[x.dataset.i18n]||x.textContent);document.documentElement.lang=e.target.value};
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase(),mod=e.ctrlKey||e.metaKey;if(mod&&k==='z'){e.preventDefault();undo()}else if((mod&&k==='y')||(mod&&e.shiftKey&&k==='z')){e.preventDefault();redo()}else if(mod&&k==='s'){e.preventDefault();open('exportModal')}else if(k==='b'&&!mod){state.tool='brush';setToolButton('brush')}else if(k==='p'&&!mod){state.tool='pencil';setToolButton('pencil')}else if(k==='e'&&!mod){state.tool='eraser';setToolButton('eraser')}else if(k==='g'&&!mod){state.tool='fill';setToolButton('fill')}else if(k==='i'&&!mod){state.tool='picker';setToolButton('picker')}else if(k==='l'&&!mod){state.tool='line';setToolButton('line')}else if(k==='r'&&!mod){state.tool='rect';setToolButton('rect')}else if(k==='o'&&!mod){state.tool='circle';setToolButton('circle')}else if(k==='t'&&!mod){state.tool='text';setToolButton('text')}else if(k==='m'&&!mod){state.tool='move';setToolButton('move')}else if(k==='f'&&!mod){document.documentElement.requestFullscreen?.()}else if(k==='['){state.size=Math.max(1,state.size-1);$('#size').value=state.size;$('#sizeOut').textContent=state.size}else if(k===']'){state.size=Math.min(100,state.size+1);$('#size').value=state.size;$('#sizeOut').textContent=state.size}else if(k==='x'&&!mod){$('#swapColors').click()}else if(k==='d'&&!mod){$('#resetColors').click()}else if(k==='escape'){$$('.modal').forEach(x=>x.classList.add('hidden'))}});
function setToolButton(t){$$('.tool').forEach(x=>x.classList.toggle('active',x.dataset.tool===t))}
setupCanvas();
